version: "3.9"
networks:
  custom_network:
    name: custom_network
    ipam:
      config:
        - subnet: 10.31.31.0/24
          gateway: 10.31.31.1
services:
  password_generator:
    image: "password_generator"
    container_name: password_generator
    hostname: password_generator.local
    restart: always
    networks:
      custom_network:
        ipv4_address: 10.31.31.2
    ports:
      - 5000:5000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"